# Generated by Django 5.2.3 on 2025-06-21 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CambioEstadoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('dado_de_baja', 'Dado de Baja'), ('en_espera', 'En Espera de Reparación')], max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('dado_de_baja', 'Dado de Baja'), ('en_espera', 'En Espera de Reparación')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo del cambio de estado')),
            ],
            options={
                'verbose_name': 'Cambio de Estado',
                'verbose_name_plural': 'Cambios de Estado',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código institucional del equipo (ej: LAB-0001)', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código debe tener el formato ABC-1234 (2-4 letras, guion, 4-8 números)', regex='^[A-Z]{2,4}-\\d{4,8}$')])),
                ('tipo_equipo', models.CharField(choices=[('computadora_escritorio', 'Computadora de Escritorio'), ('laptop', 'Laptop'), ('impresora', 'Impresora'), ('proyector', 'Proyector'), ('scanner', 'Escáner'), ('servidor', 'Servidor'), ('switch', 'Switch de Red'), ('router', 'Router'), ('ups', 'UPS/Regulador'), ('monitor', 'Monitor'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('camara', 'Cámara Web'), ('bocinas', 'Bocinas/Altavoces'), ('microfono', 'Micrófono'), ('tablet', 'Tablet'), ('disco_externo', 'Disco Duro Externo'), ('otro', 'Otro')], help_text='Tipo de equipo', max_length=30)),
                ('marca', models.CharField(help_text='Marca del equipo', max_length=50)),
                ('modelo', models.CharField(help_text='Modelo específico del equipo', max_length=50)),
                ('numero_serie', models.CharField(help_text='Número de serie del fabricante', max_length=100, unique=True)),
                ('ubicacion', models.CharField(choices=[('laboratorio_computo', 'Laboratorio de Cómputo'), ('laboratorio_redes', 'Laboratorio de Redes'), ('aula_clase', 'Aula de Clases'), ('oficina_administrativa', 'Oficina Administrativa'), ('biblioteca', 'Biblioteca'), ('auditorio', 'Auditorio'), ('sala_profesores', 'Sala de Profesores'), ('decanato', 'Decanato'), ('secretaria', 'Secretaría'), ('centro_computo', 'Centro de Cómputo'), ('almacen', 'Almacén'), ('otra', 'Otra Ubicación')], help_text='Ubicación habitual del equipo', max_length=30)),
                ('ubicacion_detalle', models.CharField(blank=True, help_text='Detalles específicos de la ubicación (ej: Aula 201, Escritorio 3)', max_length=200)),
                ('estado_actual', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('dado_de_baja', 'Dado de Baja'), ('en_espera', 'En Espera de Reparación')], default='operativo', help_text='Estado actual del equipo', max_length=20)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del equipo')),
                ('especificaciones', models.JSONField(blank=True, default=dict, help_text='Especificaciones técnicas en formato JSON')),
                ('fecha_adquisicion', models.DateField(blank=True, help_text='Fecha de adquisición del equipo', null=True)),
                ('valor_adquisicion', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de adquisición en bolívares', max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['codigo'],
            },
        ),
    ]
