# Generated by Django 5.2.3 on 2025-11-20 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='App Gestión de Reparaciones', max_length=200)),
                ('timezone', models.CharField(default='America/Caracas', max_length=64)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('password_expiry', models.PositiveIntegerField(default=90)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('two_factor', models.BooleanField(default=False)),
                ('activity_log', models.BooleanField(default=True)),
                ('backup_frequency', models.CharField(choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensualmente')], default='weekly', max_length=16)),
                ('backup_day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], default='friday', max_length=16)),
                ('backup_time', models.TimeField(blank=True, default=datetime.time(2, 0), null=True)),
                ('upload_to_cloud', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, default='2.1.5', max_length=32)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
            },
        ),
    ]
