# Generated by Django 5.2.3 on 2025-06-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestadoequipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='propietario',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipo',
            name='responsable_actual',
            field=models.ForeignKey(blank=True, help_text='Usuario que actualmente tiene el equipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipos_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cambioestadoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_estado', to='equipment.equipo'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['codigo'], name='equipment_e_codigo_aed13c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['tipo_equipo'], name='equipment_e_tipo_eq_ea3986_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['estado_actual'], name='equipment_e_estado__d37d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['ubicacion'], name='equipment_e_ubicaci_6dcba8_idx'),
        ),
    ]
