# Generated by Django 5.2.3 on 2025-06-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='equipo',
            new_name='equipos_codigo_1d1c99_idx',
            old_name='equipment_e_codigo_aed13c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipo',
            new_name='equipos_tipo_eq_03da6b_idx',
            old_name='equipment_e_tipo_eq_ea3986_idx',
        ),
        migrations.RenameIndex(
            model_name='equipo',
            new_name='equipos_estado__68baaf_idx',
            old_name='equipment_e_estado__d37d8c_idx',
        ),
        migrations.RenameIndex(
            model_name='equipo',
            new_name='equipos_ubicaci_03b9a1_idx',
            old_name='equipment_e_ubicaci_6dcba8_idx',
        ),
        migrations.AlterModelTable(
            name='cambioestadoequipo',
            table='cambios_estado_equipo',
        ),
        migrations.AlterModelTable(
            name='equipo',
            table='equipos',
        ),
    ]
