# Generated by Django 5.2.3 on 2025-07-16 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_rename_equipment_e_codigo_aed13c_idx_equipos_codigo_1d1c99_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='ubicacion_detalle',
        ),
        migrations.AddField(
            model_name='equipo',
            name='dependencia',
            field=models.CharField(blank=True, help_text='Dependencia específica del equipo (ej: Coordinaciones de informática, Administración)', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(choices=[('barinas', 'Cede: Barinas'), ('barinitas', 'Cede: Barinitas'), ('pedraza', 'Cede: Pedraza'), ('socopo', 'Cede: Socopó'), ('laboratorio_computo', 'Laboratorio de Cómputo'), ('laboratorio_redes', 'Laboratorio de Redes'), ('aula_clase', 'Aula de Clases'), ('oficina_administrativa', 'Oficina Administrativa'), ('biblioteca', 'Biblioteca'), ('auditorio', 'Auditorio'), ('sala_profesores', 'Sala de Profesores'), ('decanato', 'Decanato'), ('secretaria', 'Secretaría'), ('centro_computo', 'Centro de Cómputo'), ('almacen', 'Almacén'), ('otra', 'Otra Ubicación')], help_text='Ubicación habitual del equipo', max_length=30),
        ),
        migrations.CreateModel(
            name='HistorialReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reparacion', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.TextField(help_text='Descripción de la reparación realizada')),
                ('estado_antes', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('dado_de_baja', 'Dado de Baja'), ('en_espera', 'En Espera de Reparación')], help_text='Estado del equipo antes de la reparación', max_length=20)),
                ('estado_después', models.CharField(choices=[('operativo', 'Operativo'), ('en_mantenimiento', 'En Mantenimiento'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('dado_de_baja', 'Dado de Baja'), ('en_espera', 'En Espera de Reparación')], help_text='Estado del equipo después de la reparación', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reparaciones', to='equipment.equipo')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reparaciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reparación',
                'verbose_name_plural': 'Historial de Reparaciones',
                'ordering': ['-fecha_reparacion'],
            },
        ),
    ]
