# Generated by Django 5.2.3 on 2025-07-16 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_equipo_ubicacion_detalle_equipo_dependencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='dependencia',
            field=models.CharField(choices=[('coordinacion', 'Coordinación'), ('carsce', 'CARSCE'), ('administracion', 'Administración'), ('recursos_humanos', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('mantenimiento', 'Mantenimiento'), ('biblioteca', 'Biblioteca'), ('laboratorio', 'Laboratorio'), ('otro', 'Otra Dependencia')], help_text='Dependencia específica del equipo ', max_length=30),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(choices=[('barinas', 'Cede: Barinas'), ('barinitas', 'Cede: Barinitas'), ('pedraza', 'Cede: Pedraza'), ('socopo', 'Cede: Socopó'), ('otra', 'Otra Ubicación')], help_text='Ubicación habitual del equipo', max_length=30),
        ),
        migrations.AddIndex(
            model_name='equipo',
            index=models.Index(fields=['dependencia'], name='equipos_depende_e002cb_idx'),
        ),
    ]
