# Generated by Django 5.2.3 on 2025-07-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipo_dependencia_alter_equipo_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='equipo',
            name='equipos_depende_e002cb_idx',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='dependencia',
            field=models.CharField(blank=True, help_text='Dependencia específica del equipo (ej: Coordinaciones de informática, Administración)', max_length=200),
        ),
    ]
