# Generated by Django 5.2.3 on 2025-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_remove_equipo_equipos_depende_e002cb_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(choices=[('barinas', 'Sede: Barinas'), ('barinitas', 'Sede: Barinitas'), ('pedraza', 'Sede: Pedraza'), ('socopo', 'Sede: Socopó'), ('otra', 'Otra Sede')], help_text='Ubicación habitual del equipo', max_length=30),
        ),
    ]
