# Generated by Django 5.2.3 on 2025-06-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('coornidador', 'Coordinador'), ('administrativo', 'Personal Administrativo'), ('obrero', 'Personal Obrero'), ('tecnico', 'Tecnico'), ('otro', 'Otro')], default='Personal Administrativo', help_text='Cargo  o funcio que desempeña el usuario', max_length=50),
        ),
    ]
