# Generated by Django 5.2.3 on 2025-06-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_cargo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='usuarios',
        ),
        migrations.AlterModelTable(
            name='logacceso',
            table='registros_acceso',
        ),
    ]
