# Generated by Django for email verification token
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verification_token',
            field=models.CharField(max_length=64, blank=True, null=True, help_text='Token para la verificación de correo electrónico'),
        ),
    ]
