# Generated by Django 5.2.3 on 2025-07-14 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_is_email_verified'),
        ('users', '0003_alter_customuser_table_alter_logacceso_table'),
    ]

    operations = [
    ]
