# Generated by Django 5.2.3 on 2025-07-14 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_email_verification_token'),
        ('users', '0004_merge_20250713_2216'),
    ]

    operations = [
    ]
