# Generated by Django 5.2.3 on 2025-07-14 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250713_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indica si el usuario ha verificado su email (usado en login y registro)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(choices=[('docente', 'Docente'), ('coordinador', 'Coordinador'), ('administrativo', 'Peronal Administrativo'), ('tecnico', 'Tecnico')], default='Docente', help_text='Seleccione el cargo o función que desempeña el usuario', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(help_text='Número de celular de contacto', max_length=20, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener entre 9 y 15 dígitos', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
