# Generated by Django 5.2.3 on 2025-06-21 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialReparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del evento')),
                ('tipo_evento', models.CharField(choices=[('creacion', 'Creación del Reporte'), ('asignacion', 'Asignación a Técnico'), ('inicio_diagnostico', 'Inicio de Diagnóstico'), ('diagnostico_completado', 'Diagnóstico Completado'), ('inicio_reparacion', 'Inicio de Reparación'), ('pausa_reparacion', 'Pausa en Reparación'), ('continuacion_reparacion', 'Continuación de Reparación'), ('solicitud_repuestos', 'Solicitud de Repuestos'), ('instalacion_repuestos', 'Instalación de Repuestos'), ('pruebas', 'Realización de Pruebas'), ('reparacion_completada', 'Reparación Completada'), ('no_reparable', 'Declarado No Reparable'), ('entrega_equipo', 'Entrega del Equipo'), ('cierre_reporte', 'Cierre del Reporte'), ('reapertura', 'Reapertura del Reporte'), ('cancelacion', 'Cancelación del Reporte'), ('otro', 'Otro Evento')], help_text='Tipo de evento registrado', max_length=30)),
                ('descripcion', models.TextField(help_text='Descripción detallada del evento')),
                ('diagnostico_tecnico', models.TextField(blank=True, help_text='Diagnóstico técnico detallado')),
                ('acciones_realizadas', models.TextField(blank=True, help_text='Acciones específicas realizadas')),
                ('repuestos_utilizados', models.TextField(blank=True, help_text='Lista de repuestos utilizados')),
                ('tiempo_empleado', models.DurationField(blank=True, help_text='Tiempo empleado en horas y minutos', null=True)),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, help_text='Costo de los repuestos utilizados', max_digits=10, null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Archivo adjunto (foto, documento, etc.)', null=True, upload_to='historial_reparaciones/')),
            ],
            options={
                'verbose_name': 'Historial de Reparación',
                'verbose_name_plural': 'Historiales de Reparación',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reporte', models.CharField(editable=False, help_text='Número único del reporte (generado automáticamente)', max_length=20, unique=True)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del reporte')),
                ('descripcion_falla', models.TextField(help_text='Descripción detallada del problema reportado')),
                ('tipo_falla', models.CharField(choices=[('hardware', 'Falla de Hardware'), ('software', 'Falla de Software'), ('conectividad', 'Problemas de Conectividad'), ('rendimiento', 'Problemas de Rendimiento'), ('configuracion', 'Problemas de Configuración'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('actualizacion', 'Actualización/Upgrade'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], default='otro', help_text='Tipo de falla reportada', max_length=30)),
                ('estado_reporte', models.CharField(choices=[('en_espera', 'En Espera'), ('asignado', 'Asignado a Técnico'), ('en_diagnostico', 'En Diagnóstico'), ('en_mantenimiento', 'En Mantenimiento'), ('esperando_repuestos', 'Esperando Repuestos'), ('reparado', 'Reparado'), ('no_reparable', 'No Reparable'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='en_espera', help_text='Estado actual del reporte', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', help_text='Prioridad del reporte', max_length=10)),
                ('condiciones_falla', models.TextField(blank=True, help_text='Condiciones en las que se presenta la falla')),
                ('pasos_reproducir', models.TextField(blank=True, help_text='Pasos para reproducir la falla')),
                ('intentos_solucion', models.TextField(blank=True, help_text='Intentos de solución realizados por el usuario')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('fecha_asignacion', models.DateTimeField(blank=True, help_text='Fecha de asignación a técnico', null=True)),
                ('fecha_inicio_reparacion', models.DateTimeField(blank=True, help_text='Fecha de inicio de reparación', null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Fecha de finalización', null=True)),
                ('calificacion_servicio', models.IntegerField(blank=True, help_text='Calificación del servicio (1-5 estrellas)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_calificacion', models.TextField(blank=True, help_text='Comentario sobre la calificación del servicio')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo_parte', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=50)),
                ('stock_actual', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proveedor', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Repuesto',
                'verbose_name_plural': 'Repuestos',
                'ordering': ['nombre'],
            },
        ),
    ]
