# Generated by Django 5.2.3 on 2025-06-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0002_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialreparacion',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que registra el evento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='equipo',
            field=models.ForeignKey(help_text='Equipo reportado', on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='equipment.equipo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, help_text='Técnico asignado para la reparación', limit_choices_to={'rol': 'tecnico'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario_reporta',
            field=models.ForeignKey(help_text='Usuario que reporta la falla', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialreparacion',
            name='reporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='maintenance.reporte'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['numero_reporte'], name='maintenance_numero__2e4489_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['estado_reporte'], name='maintenance_estado__28ae7a_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['prioridad'], name='maintenance_priorid_7dd3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['fecha_reporte'], name='maintenance_fecha_r_fe18c9_idx'),
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['tecnico_asignado'], name='maintenance_tecnico_fd7b03_idx'),
        ),
        migrations.AddIndex(
            model_name='historialreparacion',
            index=models.Index(fields=['reporte', '-fecha_evento'], name='maintenance_reporte_e54df1_idx'),
        ),
        migrations.AddIndex(
            model_name='historialreparacion',
            index=models.Index(fields=['tipo_evento'], name='maintenance_tipo_ev_45243d_idx'),
        ),
    ]
