# Generated by Django 5.2.3 on 2025-06-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='historialreparacion',
            new_name='historial_r_reporte_17baf4_idx',
            old_name='maintenance_reporte_e54df1_idx',
        ),
        migrations.RenameIndex(
            model_name='historialreparacion',
            new_name='historial_r_tipo_ev_a508a1_idx',
            old_name='maintenance_tipo_ev_45243d_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='reportes_numero__99a98b_idx',
            old_name='maintenance_numero__2e4489_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='reportes_estado__2687d2_idx',
            old_name='maintenance_estado__28ae7a_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='reportes_priorid_3ce1a4_idx',
            old_name='maintenance_priorid_7dd3f8_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='reportes_fecha_r_3bbd60_idx',
            old_name='maintenance_fecha_r_fe18c9_idx',
        ),
        migrations.RenameIndex(
            model_name='reporte',
            new_name='reportes_tecnico_4d49ce_idx',
            old_name='maintenance_tecnico_fd7b03_idx',
        ),
        migrations.AlterModelTable(
            name='historialreparacion',
            table='historial_reparaciones',
        ),
        migrations.AlterModelTable(
            name='reporte',
            table='reportes',
        ),
        migrations.AlterModelTable(
            name='repuesto',
            table='repuestos',
        ),
    ]
