# Generated by Django 5.2.3 on 2025-09-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código Institucional')),
                ('tipo_equipo', models.CharField(choices=[('computadora_escritorio', 'Computadora de Escritorio'), ('laptop', 'Laptop'), ('impresora', 'Impresora'), ('proyector', 'Proyector'), ('scanner', 'Escáner'), ('servidor', 'Servidor'), ('switch', 'Switch de Red'), ('router', 'Router'), ('ups', 'UPS/Regulador'), ('monitor', 'Monitor'), ('teclado', 'Teclado'), ('mouse', 'Mouse'), ('camara', 'Cámara Web'), ('bocinas', 'Bocinas/Altavoces'), ('microfono', 'Micrófono'), ('tablet', 'Tablet'), ('disco_externo', 'Disco Duro Externo'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Equipo')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('ubicacion', models.CharField(choices=[('barinas', 'Sede: Barinas'), ('barinitas', 'Sede: Barinitas'), ('pedraza', 'Sede: Pedraza'), ('socopo', 'Sede: Socopó'), ('otra', 'Otra Sede')], max_length=20, verbose_name='Ubicación')),
                ('dependencia', models.CharField(blank=True, max_length=100, verbose_name='Dependencia')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('nombre_cliente', models.CharField(max_length=50, verbose_name='Nombre del Cliente')),
                ('apellido_cliente', models.CharField(max_length=50, verbose_name='Apellido del Cliente')),
                ('departamento_cliente', models.CharField(blank=True, max_length=100, verbose_name='Departamento del Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del Cliente')),
                ('correo_cliente', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico del Cliente')),
                ('descripcion_falla', models.TextField(verbose_name='Descripción de la Falla')),
                ('tipo_falla', models.CharField(choices=[('hardware', 'Falla de Hardware'), ('software', 'Falla de Software'), ('conectividad', 'Problemas de Conectividad'), ('rendimiento', 'Problemas de Rendimiento'), ('configuracion', 'Problemas de Configuración'), ('mantenimiento_preventivo', 'Mantenimiento Preventivo'), ('actualizacion', 'Actualización/Upgrade'), ('limpieza', 'Limpieza'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo de Falla')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=10, verbose_name='Prioridad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
