# Generated by Django 5.2.3 on 2025-09-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichaentrada',
            name='prioridad',
        ),
    ]
