# Generated by Django 5.2.3 on 2025-10-07 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_fichaentrada_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaentrada',
            name='tecnico_asignado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Técnico Asignado'),
        ),
    ]
