# Generated by Django 5.2.3 on 2025-10-07 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_fichaentrada_tecnico_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichaentrada',
            name='tecnico_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Asignado'),
        ),
    ]
