# Generated by Django 5.2.3 on 2025-11-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_fichaentrada_tecnico_asignado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaentrada',
            name='cedula_cliente',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cédula del Cliente'),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('recepcion', 'Recepción'), ('diagnostico', 'Diagnóstico'), ('reparacion', 'Reparación'), ('pruebas', 'Pruebas de Calidad'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('otro', 'Otro')], default='recepcion', max_length=30, verbose_name='Estado')),
                ('progreso', models.PositiveSmallIntegerField(default=0, verbose_name='Progreso (%)')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha Estimada')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción general')),
                ('timeline', models.JSONField(blank=True, default=list, verbose_name='Timeline')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='reports.fichaentrada', verbose_name='Ficha de Entrada')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimientos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico asignado')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
