# Generated by Django 5.2.3 on 2025-11-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_fichaentrada_cedula_cliente_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaentrada',
            name='tipo_equipo_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Equipo (otro)'),
        ),
        migrations.AddField(
            model_name='fichaentrada',
            name='tipo_falla_otro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Falla (otro)'),
        ),
        migrations.AlterField(
            model_name='fichaentrada',
            name='correo_cliente',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo del Cliente'),
        ),
    ]
