# Generated by Django 5.2.3 on 2025-11-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_fichaentrada_tipo_equipo_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaentrada',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('diagnostico', 'En Diagnóstico'), ('reparacion', 'En Reparación'), ('pruebas_calidad', 'Pruebas de Calidad'), ('listo_entrega', 'Listo para Entrega'), ('entregado', 'Entregado')], default='recibido', max_length=20, verbose_name='Estado'),
        ),
    ]
