# Generated by Django 5.2.3 on 2025-11-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_fichaentrada_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='video',
            field=models.FileField(blank=True, help_text='Sube un video opcional. Si es más largo, se recortará a los primeros 10 segundos.', null=True, upload_to='seguimientos/videos/', verbose_name='Video (opcional)'),
        ),
    ]
