# Generated by Django 5.2.3 on 2025-11-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_seguimiento_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.JSONField(default=list, verbose_name='Destinatarios')),
                ('subject', models.CharField(max_length=255, verbose_name='Asunto')),
                ('body_text', models.TextField(verbose_name='Cuerpo (texto)')),
                ('body_html', models.TextField(blank=True, verbose_name='Cuerpo (html)')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Intentos')),
                ('last_error', models.TextField(blank=True, verbose_name='Último error')),
                ('send_after', models.DateTimeField(blank=True, null=True, verbose_name='Reintentar después de')),
                ('sent', models.BooleanField(default=False, verbose_name='Enviado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Correo en cola',
                'verbose_name_plural': 'Correos en cola',
            },
        ),
    ]
